SampleMVC/Models/Entities/Skill.cs
namespace SampleMVC.Models.Entities;

public class Skill
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string UserId { get; set; }
    public string Title { get; set; }
    public string Text { get; set; }
    public DateTime CreatedAt { get; set; }

    public User User { get; set; }
}

SampleMVC/Models/Entities/User.cs
namespace SampleMVC.Models.Entities;

public class User
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string Name { get; set; }
    public string Email { get; set; }
    public string About { get; set; }
    public string? Image { get; set; }
    public string? Resume { get; set; }
    public DateTime CreatedAt { get; set; }

    public IEnumerable<Skill> Skills { get; set; }
}

SampleMVC/Models/ErrorViewModel.cs
namespace SampleMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

SampleMVC/Models/HomePageVM.cs
namespace SampleMVC.Models;

public class HomePageVM
{
    public string Name { get; set; }
    public string Image { get; set; }
    public string JobTitle { get; set; }
    public string Description { get; set; }
    public IEnumerable<Skill> Skills { get; set; }
    public IEnumerable<Portfolio> Portfolios { get; set; }
}

public class Skill
{
    public string Title { get; set; }
    public string Description { get; set; }
}

public class Portfolio
{
    public string Title { get; set; }
    public string Description { get; set; }
}

SampleMVC/Models/UserVM.cs
namespace SampleMVC.Models;

public class UserVM
{
    public string Name { get; set; }
    public string? Image { get; set; }
    public string Description { get; set; }
    public IEnumerable<Entities.Skill> Skills { get; set; }
}

SampleMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SampleMVC.Data.Repositories;
using SampleMVC.Models;

namespace SampleMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IUserRepository _userRepository;

    public HomeController(ILogger<HomeController> logger, IUserRepository userRepository)
    {
        _logger = logger;
        _userRepository = userRepository;
    }

    public async Task<IActionResult> Index()
    {
        var users = await _userRepository.GetAllUsers();
        
        return View(users);
    }
}

SampleMVC/Controllers/SkillController.cs
using Microsoft.AspNetCore.Mvc;
using SampleMVC.Data.Dtos;
using SampleMVC.Data.Repositories;
using SampleMVC.Models.Entities;

namespace SampleMVC.Controllers;

[Route("skills")]
public class SkillController : Controller
{
    private readonly ISkillRepository _skillRepository;

    public SkillController(ISkillRepository skillRepository)
    {
        _skillRepository = skillRepository;
    }

    [HttpGet("{userId}")]
    public IActionResult AddSkill(string userId)
    {
        ViewBag.UserId = userId;
        return View();
    }

    [HttpPost("{userId}")]
    public async Task<IActionResult> AddSkill(string userId, [FromForm] AddSkillDto addSkillDto)
    {
        var skill = new Skill
        {
            UserId = userId,
            Title = addSkillDto.Title,
            Text = addSkillDto.Text,
            CreatedAt = DateTime.Now,
        };

        await _skillRepository.Add(skill);

        return RedirectToAction("GetUserPortfolio", "User", new {userId = userId});
    }

    [HttpGet("edit/{skillId}")]
    public async Task<IActionResult> Edit(string skillId)
    {
        var skill = await _skillRepository.GetSkillById(skillId);
        
        if (skill == null)
            return BadRequest();
        
        var skillDto = new AddSkillDto
        {
            Title = skill.Title,
            Text = skill.Text
        };
        
        ViewBag.SkillId = skillId;
        
        return View(skillDto);
    }

    [HttpPost("edit/{skillId}")]
    public async Task<IActionResult> Edit(string skillId, [FromForm] AddSkillDto editSkillDto)
    {
        var skill = await _skillRepository.GetSkillById(skillId);
        
        if (skill == null)
            return BadRequest();

        skill.Title = editSkillDto.Title;
        skill.Text = editSkillDto.Text;

        await _skillRepository.Update(skill);

        return RedirectToAction("GetUserPortfolio", "User", new {userId = skill.UserId});
    }

    [HttpPost("delete/{skillId}")]
    public async Task<IActionResult> Delete(string skillId)
    {
        var skill = await _skillRepository.GetSkillById(skillId);

        await _skillRepository.Delete(skill);

        return RedirectToAction("GetUserPortfolio", "User", new {userId = skill.UserId});
    }
}

SampleMVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using SampleMVC.Data.Dtos;
using SampleMVC.Data.Repositories;
using SampleMVC.Models;
using SampleMVC.Models.Entities;

namespace SampleMVC.Controllers;

[Route("")]
public class UserController: Controller
{
    private readonly IUserRepository _userRepository;

    public UserController(IUserRepository userRepository)
    {
        _userRepository = userRepository;
    }

    [HttpGet("{userId}")]
    public async Task<IActionResult> GetUserPortfolio(string userId)
    {
        var user = await _userRepository.GetUserWithSkillsById(userId);

        var userVm = new UserVM
        {
            Name = user.Name,
            Image = user.Image,
            Description = user.About,
            Skills = user.Skills,
        };

        ViewBag.UserId = userId;
        
        return View(userVm);
    }

    [HttpGet("register")]
    public IActionResult CreateUser()
    {
        return View();
    }

    [HttpPost("register")]
    public async Task<IActionResult> CreateUser([FromForm] UserCreationDto userDto)
    {
        var user = new User
        {
            Name = userDto.Name,
            Email = userDto.Email,
            About = userDto.About,
            CreatedAt = DateTime.Now,
        };

        var response = await _userRepository.Add(user);

        return RedirectToAction("GetUserPortfolio", new {userId = user.Id});
    }
}

SampleMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model IEnumerable<SampleMVC.Models.Entities.User>;

<section class="py-10 md:py-16">

    <div class="container max-w-screen-xl mx-auto px-4">

        <div class="flex justify-end">
            <a class="button" asp-controller="User" asp-action="CreateUser" >Create a portfolio site</a>
        </div>
        
        <div class="mt-12 flex w-full flex-col items-center space-y-5 justify-center">
            @foreach (var user in Model)
            {
                <div class="w-full h-25 text-2xl hover:bg-gray-300 hover:text-gray-700 transition duration-300 py-5 flex justify-center bg-gray-900 rounded text-gray-100">
                    <a class="text-center w-full" asp-controller="User" asp-action="GetUserPortfolio" asp-route-userId="@user.Id">
                        @user.Name
                    </a>
                </div>
            }
        </div>

    </div>

</section>

SampleMVC/Views/Home/User.cshtml
@{
    ViewData["Title"] = "User Portfolio";
}
@model UserVM;

<section class="py-10 md:py-16">

    <div class="container max-w-screen-xl mx-auto px-4">

        <nav class="flex items-center justify-between mb-40">
            <img src="/assets/image/navbar-logo.png" alt="Logo">

            <button class="px-7 py-3 md:px-9 md:py-4 bg-white font-medium md:font-semibold text-gray-700 text-md rounded-md hover:bg-gray-700 hover:text-white transition ease-linear duration-500">Get my CV</button>
        </nav>

        <div class="text-center">
            <div class="flex justify-center mb-16">
                <img src="@Model.Image" alt="Image">
            </div>

            <h6 class="font-medium text-gray-600 text-lg md:text-2xl uppercase mb-8">@Model.Name</h6>

            <p class="font-normal text-gray-600 text-md md:text-xl mb-16">@Model.Description</p>
        </div>

    </div>

</section>

<section class="py-10 md:py-16">

    <div class="container max-w-screen-xl mx-auto px-4">

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            @foreach (var skill in @Model.Skills)
            {
                <div class="bg-gray-50 px-8 py-10 rounded-md">
                    <div class="w-20 py-6 flex justify-center bg-gray-100 rounded-md mb-4">
                        <i data-feather="activity"></i>
                    </div>

                    <h4 class="font-medium text-gray-700 text-lg mb-4">@skill.Title</h4>

                    <p class="font-normal text-gray-500 text-md">@skill.Description</p>
                </div>
            }
        </div>

    </div>

</section>

<section class="py-10 md:py-16">

    <div class="container max-w-screen-xl mx-auto px-4">

        <div class="flex flex-col lg:flex-row justify-between">
            <div class="mb-10 lg:mb-0">
                <h1 class="font-medium text-gray-700 text-3xl md:text-4xl mb-5">Portfolio</h1>

                <p class="font-normal text-gray-500 text-xs md:text-base">I have brought here my biggest and favorite works <br> as a professional.</p>
            </div>
        </div>

    </div>

</section>

SampleMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SampleMVC</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.28.0/feather.min.js" integrity="sha512-7x3zila4t2qNycrtZ31HO0NnJr8kg2VI67YLoRSyi9hGhRN66FHYWr7Axa9Y1J9tGYHVBPqIjSE1ogHrJTz51g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body class="text-gray-800 antialiased">
@RenderBody()


<footer class="py-10 md:py-16 mb-20 md:mb-40 lg::mb-52">

    <div class="container max-w-screen-xl mx-auto px-4">


    </div>

</footer>
<script>
    feather.replace()
</script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SampleMVC/Views/Skill/AddSkill.cshtml
@model SampleMVC.Data.Dtos.AddSkillDto;

<div class="min-h-screen flex items-center justify-center bg-gray-100">
    <div class="px-8 py-6 mx-4 mt-4 text-left bg-white rounded-2xl shadow-lg md:w-1/3 lg:w-1/3 sm:w-1/3">
        <h3 class="text-2xl font-bold font-med text-center">Set Up Skill</h3>
        
        <form method="post" asp-action="AddSkill" asp-controller="Skill" asp-route-userId="@ViewBag.UserId">
            <div class="mt-4">
                <div>
                    <label class="label" for="Title">Title</label>
                    <input type="text" asp-for="Title" required placeholder="Enter skill title" class="input">
                    <span asp-validation-for="Title" class="text-red-500 text-xs"></span>
                </div>

                <div class="mt-4 mb-4">
                    <label class="label" for="Text">Text</label>
                    <textarea required rows="5" asp-for="Text" placeholder="Enter skill description" class="input"></textarea>
                    <span asp-validation-for="Text" class="text-red-500 text-xs"></span>
                </div>

                <div class="flex mt-4">
                    <button type="submit" class="w-full button">Add</button>
                </div>
            </div>
        </form>
    </div>
</div>

SampleMVC/Views/Skill/Edit.cshtml
@model SampleMVC.Data.Dtos.AddSkillDto;

<div class="min-h-screen flex items-center justify-center bg-gray-100">
    <div class="px-8 py-6 mx-4 mt-4 text-left bg-white rounded-2xl shadow-lg md:w-1/3 lg:w-1/3 sm:w-1/3">
        <h3 class="text-2xl font-bold font-med text-center">Set Up Skill</h3>
        
        <form method="post" asp-action="Edit" asp-controller="Skill" asp-route-userId="@ViewBag.UserId">
            <div class="mt-4">
                <div>
                    <label class="label" for="Title">Title</label>
                    <input type="text" asp-for="Title" required placeholder="Enter skill title" class="input">
                    <span asp-validation-for="Title" class="text-red-500 text-xs"></span>
                </div>

                <div class="mt-4 mb-4">
                    <label class="label" for="Text">Text</label>
                    <textarea required rows="5" asp-for="Text" placeholder="Enter skill description" class="input"></textarea>
                    <span asp-validation-for="Text" class="text-red-500 text-xs"></span>
                </div>

                <div class="flex mt-4">
                    <button type="submit" class="w-full button">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>

SampleMVC/Views/User/CreateUser.cshtml
@model SampleMVC.Data.Dtos.UserCreationDto;

<div class="min-h-screen flex items-center justify-center bg-gray-100">
    <div class="px-8 py-6 mx-4 mt-4 text-left bg-white rounded-2xl shadow-lg md:w-1/3 lg:w-1/3 sm:w-1/3">
        <h3 class="text-2xl font-bold font-med text-center">Set Up Your Personal Portfolio</h3>

        <form method="post" asp-action="CreateUser" asp-controller="User">
            <div class="mt-4">
                <div>
                    <label class="label" for="Name">First Name</label>
                    <input type="text" asp-for="Name" required placeholder="Enter your full names" class="input">
                    <span asp-validation-for="Name" class="text-red-500 text-xs"></span>
                </div>

                <div class="mt-4 mb-4">
                    <label class="label" for="Email">Email Address</label>
                    <input type="email" required asp-for="Email" placeholder="Enter your email" class="input">
                    <span asp-validation-for="Email" class="text-red-500 text-xs"></span>
                </div>

                <div>
                    <label class="label" for="About">About You</label>
                    <input type="text" required asp-for="About" placeholder="Enter your full names" class="input">
                    <span asp-validation-for="About" class="text-red-500 text-xs"></span>
                </div>

                <div>
                    <label class="label" for="Image">Image</label>
                    <input type="file" asp-for="Image" class="input">
                    <span asp-validation-for="Image" class="text-red-500 text-xs"></span>
                </div>

                <div>
                    <label class="label" for="Resume">Resume</label>
                    <input type="file" asp-for="Resume" class="input">
                    <span asp-validation-for="Resume" class="text-red-500 text-xs"></span>
                </div>


                <div class="flex mt-4">
                    <button type="submit" class="w-full button">Register</button>
                </div>
            </div>
        </form>
    </div>
</div>

SampleMVC/Views/User/GetUserPortfolio.cshtml
@{
    ViewData["Title"] = "User Portfolio";
}
@model UserVM;

<section class="py-10 md:py-16">

    <div class="container max-w-screen-xl mx-auto px-4">

        <nav class="flex items-center justify-between mb-40">
            <a href="/">
                <img src="/assets/image/navbar-logo.png" alt="Logo">
            </a>

            <a asp-controller="Skill" asp-action="AddSkill" asp-route-userId="@ViewBag.UserId" class="px-7 py-3 md:px-9 md:py-4 bg-white font-medium md:font-semibold text-gray-700 text-md rounded-md hover:bg-gray-700 hover:text-white transition ease-linear duration-500">Add Skill</a>
        </nav>

        <div class="text-center">
            <div class="flex justify-center mb-16">
                <img src="@Model.Image" alt="Image">
            </div>

            <h6 class="font-medium text-gray-600 text-lg md:text-2xl uppercase mb-8">@Model.Name</h6>

            <p class="font-normal text-gray-600 text-md md:text-xl mb-16">@Model.Description</p>
        </div>

    </div>

</section>

<section class="py-10 md:py-16">

    <div class="container max-w-screen-xl mx-auto px-4">

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            @foreach (var skill in @Model.Skills)
            {
                <a asp-controller="Skill" asp-action="Edit" asp-route-skillId="@skill.Id" class="block relative bg-gray-50 px-8 py-10 rounded-md">
                    <div class="w-20 py-6 flex justify-center bg-gray-100 rounded-md mb-4">
                        <i data-feather="activity"></i>
                    </div>
                    
                    <form method="post" asp-controller="Skill" asp-action="Delete" asp-route-skillId="@skill.Id">
                        <button type="submit" class="absolute z-10 top-12 right-5 button-secondary hover:bg-red-700 bg-red-600 text-gray-100">Delete</button>
                    </form>

                    <h4 class="font-medium text-gray-700 text-lg mb-4">@skill.Title</h4>

                    <p class="font-normal text-gray-500 text-md">@skill.Text </p>
                </a>
            }
        </div>

    </div>

</section>